# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

env:
  global:
    - Run_RPushbullet_Tests="yes"
    - Run_RPushbullet_Tests_All="yes"

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap
  # decrypt the file .rpushbullet.json, cf https://docs.travis-ci.com/user/encrypting-files/
  - openssl aes-256-cbc -K $encrypted_988d19a907a0_key -iv $encrypted_988d19a907a0_iv -in .rpushbullet.json.enc -out ~/.rpushbullet.json -d
  
install:
  - ./run.sh install_aptget r-cran-curl r-cran-jsonlite

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

after_success:
  - ./run.sh coverage
   
notifications:
  email:
    on_success: change
    on_failure: change

